# syntax=docker/dockerfile:1
FROM debian:12-slim
RUN apt-get update && apt-get install -y --no-install-recommends coreutils && rm -rf /var/lib/apt/lists/*
COPY pxe/static/blobs/internal/x86_64 /artifacts/blobs/internal/x86_64
