// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the IssuerClaimMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuerClaimMapping{}

// IssuerClaimMapping Mapping from custom issuer token claims to NICo organization and role data. Each mapping must specify either `orgName` for a static organization or `orgAttribute` for a dynamic organization. Roles come from either the static `roles` list, `rolesAttribute`, or `isServiceAccount: true`.
type IssuerClaimMapping struct {
	// JWT claim path to extract the organization name for dynamic mappings.
	OrgAttribute *string `json:"orgAttribute,omitempty"`
	// JWT claim path to extract the organization display name for dynamic mappings.
	OrgDisplayAttribute *string `json:"orgDisplayAttribute,omitempty"`
	// Fixed organization name for static mappings.
	OrgName *string `json:"orgName,omitempty"`
	// Display name for a static organization mapping.
	OrgDisplayName *string `json:"orgDisplayName,omitempty"`
	// JWT claim path to extract role names.
	RolesAttribute *string `json:"rolesAttribute,omitempty"`
	// Static NICo role names assigned for this mapping.
	Roles []string `json:"roles,omitempty"`
	// Whether this mapping authenticates tokens as service accounts. Only supported when the API runs in disconnected mode.
	IsServiceAccount *bool `json:"isServiceAccount,omitempty"`
}

// NewIssuerClaimMapping instantiates a new IssuerClaimMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuerClaimMapping() *IssuerClaimMapping {
	this := IssuerClaimMapping{}
	var isServiceAccount bool = false
	this.IsServiceAccount = &isServiceAccount
	return &this
}

// NewIssuerClaimMappingWithDefaults instantiates a new IssuerClaimMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerClaimMappingWithDefaults() *IssuerClaimMapping {
	this := IssuerClaimMapping{}
	var isServiceAccount bool = false
	this.IsServiceAccount = &isServiceAccount
	return &this
}

// GetOrgAttribute returns the OrgAttribute field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetOrgAttribute() string {
	if o == nil || IsNil(o.OrgAttribute) {
		var ret string
		return ret
	}
	return *o.OrgAttribute
}

// GetOrgAttributeOk returns a tuple with the OrgAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetOrgAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.OrgAttribute) {
		return nil, false
	}
	return o.OrgAttribute, true
}

// HasOrgAttribute returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasOrgAttribute() bool {
	if o != nil && !IsNil(o.OrgAttribute) {
		return true
	}

	return false
}

// SetOrgAttribute gets a reference to the given string and assigns it to the OrgAttribute field.
func (o *IssuerClaimMapping) SetOrgAttribute(v string) {
	o.OrgAttribute = &v
}

// GetOrgDisplayAttribute returns the OrgDisplayAttribute field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetOrgDisplayAttribute() string {
	if o == nil || IsNil(o.OrgDisplayAttribute) {
		var ret string
		return ret
	}
	return *o.OrgDisplayAttribute
}

// GetOrgDisplayAttributeOk returns a tuple with the OrgDisplayAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetOrgDisplayAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDisplayAttribute) {
		return nil, false
	}
	return o.OrgDisplayAttribute, true
}

// HasOrgDisplayAttribute returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasOrgDisplayAttribute() bool {
	if o != nil && !IsNil(o.OrgDisplayAttribute) {
		return true
	}

	return false
}

// SetOrgDisplayAttribute gets a reference to the given string and assigns it to the OrgDisplayAttribute field.
func (o *IssuerClaimMapping) SetOrgDisplayAttribute(v string) {
	o.OrgDisplayAttribute = &v
}

// GetOrgName returns the OrgName field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetOrgName() string {
	if o == nil || IsNil(o.OrgName) {
		var ret string
		return ret
	}
	return *o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetOrgNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrgName) {
		return nil, false
	}
	return o.OrgName, true
}

// HasOrgName returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasOrgName() bool {
	if o != nil && !IsNil(o.OrgName) {
		return true
	}

	return false
}

// SetOrgName gets a reference to the given string and assigns it to the OrgName field.
func (o *IssuerClaimMapping) SetOrgName(v string) {
	o.OrgName = &v
}

// GetOrgDisplayName returns the OrgDisplayName field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetOrgDisplayName() string {
	if o == nil || IsNil(o.OrgDisplayName) {
		var ret string
		return ret
	}
	return *o.OrgDisplayName
}

// GetOrgDisplayNameOk returns a tuple with the OrgDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetOrgDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDisplayName) {
		return nil, false
	}
	return o.OrgDisplayName, true
}

// HasOrgDisplayName returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasOrgDisplayName() bool {
	if o != nil && !IsNil(o.OrgDisplayName) {
		return true
	}

	return false
}

// SetOrgDisplayName gets a reference to the given string and assigns it to the OrgDisplayName field.
func (o *IssuerClaimMapping) SetOrgDisplayName(v string) {
	o.OrgDisplayName = &v
}

// GetRolesAttribute returns the RolesAttribute field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetRolesAttribute() string {
	if o == nil || IsNil(o.RolesAttribute) {
		var ret string
		return ret
	}
	return *o.RolesAttribute
}

// GetRolesAttributeOk returns a tuple with the RolesAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetRolesAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.RolesAttribute) {
		return nil, false
	}
	return o.RolesAttribute, true
}

// HasRolesAttribute returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasRolesAttribute() bool {
	if o != nil && !IsNil(o.RolesAttribute) {
		return true
	}

	return false
}

// SetRolesAttribute gets a reference to the given string and assigns it to the RolesAttribute field.
func (o *IssuerClaimMapping) SetRolesAttribute(v string) {
	o.RolesAttribute = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *IssuerClaimMapping) SetRoles(v []string) {
	o.Roles = v
}

// GetIsServiceAccount returns the IsServiceAccount field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetIsServiceAccount() bool {
	if o == nil || IsNil(o.IsServiceAccount) {
		var ret bool
		return ret
	}
	return *o.IsServiceAccount
}

// GetIsServiceAccountOk returns a tuple with the IsServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetIsServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.IsServiceAccount) {
		return nil, false
	}
	return o.IsServiceAccount, true
}

// HasIsServiceAccount returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasIsServiceAccount() bool {
	if o != nil && !IsNil(o.IsServiceAccount) {
		return true
	}

	return false
}

// SetIsServiceAccount gets a reference to the given bool and assigns it to the IsServiceAccount field.
func (o *IssuerClaimMapping) SetIsServiceAccount(v bool) {
	o.IsServiceAccount = &v
}

func (o IssuerClaimMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuerClaimMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrgAttribute) {
		toSerialize["orgAttribute"] = o.OrgAttribute
	}
	if !IsNil(o.OrgDisplayAttribute) {
		toSerialize["orgDisplayAttribute"] = o.OrgDisplayAttribute
	}
	if !IsNil(o.OrgName) {
		toSerialize["orgName"] = o.OrgName
	}
	if !IsNil(o.OrgDisplayName) {
		toSerialize["orgDisplayName"] = o.OrgDisplayName
	}
	if !IsNil(o.RolesAttribute) {
		toSerialize["rolesAttribute"] = o.RolesAttribute
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if !IsNil(o.IsServiceAccount) {
		toSerialize["isServiceAccount"] = o.IsServiceAccount
	}
	return toSerialize, nil
}

type NullableIssuerClaimMapping struct {
	value *IssuerClaimMapping
	isSet bool
}

func (v NullableIssuerClaimMapping) Get() *IssuerClaimMapping {
	return v.value
}

func (v *NullableIssuerClaimMapping) Set(val *IssuerClaimMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerClaimMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerClaimMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerClaimMapping(val *IssuerClaimMapping) *NullableIssuerClaimMapping {
	return &NullableIssuerClaimMapping{value: val, isSet: true}
}

func (v NullableIssuerClaimMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerClaimMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
