// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"fmt"
)

// IssuerStatus Whether the issuer's JWKS was reachable during the most recent apply or boot seed attempt.
type IssuerStatus string

// List of IssuerStatus
const (
	ISSUERSTATUS_PENDING IssuerStatus = "Pending"
	ISSUERSTATUS_READY   IssuerStatus = "Ready"
)

// All allowed values of IssuerStatus enum
var AllowedIssuerStatusEnumValues = []IssuerStatus{
	"Pending",
	"Ready",
}

func (v *IssuerStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IssuerStatus(value)
	for _, existing := range AllowedIssuerStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IssuerStatus", value)
}

// NewIssuerStatusFromValue returns a pointer to a valid IssuerStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIssuerStatusFromValue(v string) (*IssuerStatus, error) {
	ev := IssuerStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IssuerStatus: valid values are %v", v, AllowedIssuerStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IssuerStatus) IsValid() bool {
	for _, existing := range AllowedIssuerStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IssuerStatus value
func (v IssuerStatus) Ptr() *IssuerStatus {
	return &v
}

type NullableIssuerStatus struct {
	value *IssuerStatus
	isSet bool
}

func (v NullableIssuerStatus) Get() *IssuerStatus {
	return v.value
}

func (v *NullableIssuerStatus) Set(val *IssuerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerStatus(val *IssuerStatus) *NullableIssuerStatus {
	return &NullableIssuerStatus{value: val, isSet: true}
}

func (v NullableIssuerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
