// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the IssuerUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuerUpdateRequest{}

// IssuerUpdateRequest Request to update a dynamic custom issuer. `issuerUrl` and `origin` are immutable.
type IssuerUpdateRequest struct {
	// Human-readable name for the issuer binding.
	Name NullableString `json:"name,omitempty"`
	// JWKS endpoint used to verify token signatures.
	JwksUrl NullableString `json:"jwksUrl,omitempty"`
	// Must be false for dynamic custom issuer registrations. Use `claimMappings[].isServiceAccount` for custom service-account mappings.
	ServiceAccount NullableBool `json:"serviceAccount,omitempty"`
	// Replacement allowed audience list. Omit the field to leave it unchanged.
	Audiences []string `json:"audiences,omitempty"`
	// Replacement required scope list. Omit the field to leave it unchanged.
	Scopes []string `json:"scopes,omitempty"`
	// JWKS fetch timeout as a Go duration string, for example `5s` or `1m`.
	JwksTimeout NullableString `json:"jwksTimeout,omitempty"`
	// Replacement claim mappings. Omit the field to leave mappings unchanged.
	ClaimMappings []IssuerClaimMapping `json:"claimMappings,omitempty"`
	// Allows this issuer's static `orgName` mappings to duplicate static org names from other issuers.
	AllowDuplicateStaticOrgNames NullableBool `json:"allowDuplicateStaticOrgNames,omitempty"`
}

// NewIssuerUpdateRequest instantiates a new IssuerUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuerUpdateRequest() *IssuerUpdateRequest {
	this := IssuerUpdateRequest{}
	return &this
}

// NewIssuerUpdateRequestWithDefaults instantiates a new IssuerUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerUpdateRequestWithDefaults() *IssuerUpdateRequest {
	this := IssuerUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IssuerUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IssuerUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IssuerUpdateRequest) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *IssuerUpdateRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IssuerUpdateRequest) UnsetName() {
	o.Name.Unset()
}

// GetJwksUrl returns the JwksUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IssuerUpdateRequest) GetJwksUrl() string {
	if o == nil || IsNil(o.JwksUrl.Get()) {
		var ret string
		return ret
	}
	return *o.JwksUrl.Get()
}

// GetJwksUrlOk returns a tuple with the JwksUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IssuerUpdateRequest) GetJwksUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JwksUrl.Get(), o.JwksUrl.IsSet()
}

// HasJwksUrl returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasJwksUrl() bool {
	if o != nil && o.JwksUrl.IsSet() {
		return true
	}

	return false
}

// SetJwksUrl gets a reference to the given NullableString and assigns it to the JwksUrl field.
func (o *IssuerUpdateRequest) SetJwksUrl(v string) {
	o.JwksUrl.Set(&v)
}

// SetJwksUrlNil sets the value for JwksUrl to be an explicit nil
func (o *IssuerUpdateRequest) SetJwksUrlNil() {
	o.JwksUrl.Set(nil)
}

// UnsetJwksUrl ensures that no value is present for JwksUrl, not even an explicit nil
func (o *IssuerUpdateRequest) UnsetJwksUrl() {
	o.JwksUrl.Unset()
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IssuerUpdateRequest) GetServiceAccount() bool {
	if o == nil || IsNil(o.ServiceAccount.Get()) {
		var ret bool
		return ret
	}
	return *o.ServiceAccount.Get()
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IssuerUpdateRequest) GetServiceAccountOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceAccount.Get(), o.ServiceAccount.IsSet()
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasServiceAccount() bool {
	if o != nil && o.ServiceAccount.IsSet() {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given NullableBool and assigns it to the ServiceAccount field.
func (o *IssuerUpdateRequest) SetServiceAccount(v bool) {
	o.ServiceAccount.Set(&v)
}

// SetServiceAccountNil sets the value for ServiceAccount to be an explicit nil
func (o *IssuerUpdateRequest) SetServiceAccountNil() {
	o.ServiceAccount.Set(nil)
}

// UnsetServiceAccount ensures that no value is present for ServiceAccount, not even an explicit nil
func (o *IssuerUpdateRequest) UnsetServiceAccount() {
	o.ServiceAccount.Unset()
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *IssuerUpdateRequest) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerUpdateRequest) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *IssuerUpdateRequest) SetAudiences(v []string) {
	o.Audiences = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *IssuerUpdateRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerUpdateRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *IssuerUpdateRequest) SetScopes(v []string) {
	o.Scopes = v
}

// GetJwksTimeout returns the JwksTimeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IssuerUpdateRequest) GetJwksTimeout() string {
	if o == nil || IsNil(o.JwksTimeout.Get()) {
		var ret string
		return ret
	}
	return *o.JwksTimeout.Get()
}

// GetJwksTimeoutOk returns a tuple with the JwksTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IssuerUpdateRequest) GetJwksTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JwksTimeout.Get(), o.JwksTimeout.IsSet()
}

// HasJwksTimeout returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasJwksTimeout() bool {
	if o != nil && o.JwksTimeout.IsSet() {
		return true
	}

	return false
}

// SetJwksTimeout gets a reference to the given NullableString and assigns it to the JwksTimeout field.
func (o *IssuerUpdateRequest) SetJwksTimeout(v string) {
	o.JwksTimeout.Set(&v)
}

// SetJwksTimeoutNil sets the value for JwksTimeout to be an explicit nil
func (o *IssuerUpdateRequest) SetJwksTimeoutNil() {
	o.JwksTimeout.Set(nil)
}

// UnsetJwksTimeout ensures that no value is present for JwksTimeout, not even an explicit nil
func (o *IssuerUpdateRequest) UnsetJwksTimeout() {
	o.JwksTimeout.Unset()
}

// GetClaimMappings returns the ClaimMappings field value if set, zero value otherwise.
func (o *IssuerUpdateRequest) GetClaimMappings() []IssuerClaimMapping {
	if o == nil || IsNil(o.ClaimMappings) {
		var ret []IssuerClaimMapping
		return ret
	}
	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerUpdateRequest) GetClaimMappingsOk() ([]IssuerClaimMapping, bool) {
	if o == nil || IsNil(o.ClaimMappings) {
		return nil, false
	}
	return o.ClaimMappings, true
}

// HasClaimMappings returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasClaimMappings() bool {
	if o != nil && !IsNil(o.ClaimMappings) {
		return true
	}

	return false
}

// SetClaimMappings gets a reference to the given []IssuerClaimMapping and assigns it to the ClaimMappings field.
func (o *IssuerUpdateRequest) SetClaimMappings(v []IssuerClaimMapping) {
	o.ClaimMappings = v
}

// GetAllowDuplicateStaticOrgNames returns the AllowDuplicateStaticOrgNames field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IssuerUpdateRequest) GetAllowDuplicateStaticOrgNames() bool {
	if o == nil || IsNil(o.AllowDuplicateStaticOrgNames.Get()) {
		var ret bool
		return ret
	}
	return *o.AllowDuplicateStaticOrgNames.Get()
}

// GetAllowDuplicateStaticOrgNamesOk returns a tuple with the AllowDuplicateStaticOrgNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IssuerUpdateRequest) GetAllowDuplicateStaticOrgNamesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowDuplicateStaticOrgNames.Get(), o.AllowDuplicateStaticOrgNames.IsSet()
}

// HasAllowDuplicateStaticOrgNames returns a boolean if a field has been set.
func (o *IssuerUpdateRequest) HasAllowDuplicateStaticOrgNames() bool {
	if o != nil && o.AllowDuplicateStaticOrgNames.IsSet() {
		return true
	}

	return false
}

// SetAllowDuplicateStaticOrgNames gets a reference to the given NullableBool and assigns it to the AllowDuplicateStaticOrgNames field.
func (o *IssuerUpdateRequest) SetAllowDuplicateStaticOrgNames(v bool) {
	o.AllowDuplicateStaticOrgNames.Set(&v)
}

// SetAllowDuplicateStaticOrgNamesNil sets the value for AllowDuplicateStaticOrgNames to be an explicit nil
func (o *IssuerUpdateRequest) SetAllowDuplicateStaticOrgNamesNil() {
	o.AllowDuplicateStaticOrgNames.Set(nil)
}

// UnsetAllowDuplicateStaticOrgNames ensures that no value is present for AllowDuplicateStaticOrgNames, not even an explicit nil
func (o *IssuerUpdateRequest) UnsetAllowDuplicateStaticOrgNames() {
	o.AllowDuplicateStaticOrgNames.Unset()
}

func (o IssuerUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuerUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.JwksUrl.IsSet() {
		toSerialize["jwksUrl"] = o.JwksUrl.Get()
	}
	if o.ServiceAccount.IsSet() {
		toSerialize["serviceAccount"] = o.ServiceAccount.Get()
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if o.JwksTimeout.IsSet() {
		toSerialize["jwksTimeout"] = o.JwksTimeout.Get()
	}
	if !IsNil(o.ClaimMappings) {
		toSerialize["claimMappings"] = o.ClaimMappings
	}
	if o.AllowDuplicateStaticOrgNames.IsSet() {
		toSerialize["allowDuplicateStaticOrgNames"] = o.AllowDuplicateStaticOrgNames.Get()
	}
	return toSerialize, nil
}

type NullableIssuerUpdateRequest struct {
	value *IssuerUpdateRequest
	isSet bool
}

func (v NullableIssuerUpdateRequest) Get() *IssuerUpdateRequest {
	return v.value
}

func (v *NullableIssuerUpdateRequest) Set(val *IssuerUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerUpdateRequest(val *IssuerUpdateRequest) *NullableIssuerUpdateRequest {
	return &NullableIssuerUpdateRequest{value: val, isSet: true}
}

func (v NullableIssuerUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
