// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IssuerCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuerCreateRequest{}

// IssuerCreateRequest Request to dynamically register a custom external OIDC issuer.
type IssuerCreateRequest struct {
	// Human-readable name for the issuer binding.
	Name string `json:"name"`
	// Expected JWT `iss` claim value. Immutable after creation.
	IssuerUrl string `json:"issuerUrl"`
	// JWKS endpoint used to verify token signatures.
	JwksUrl string `json:"jwksUrl"`
	// Dynamic registration supports only custom external issuer origins. Omit this field or set it to `custom`.
	Origin *string `json:"origin,omitempty"`
	// Must be false for dynamic custom issuer registrations. Use `claimMappings[].isServiceAccount` for custom service-account mappings.
	ServiceAccount *bool `json:"serviceAccount,omitempty"`
	// Allowed token audiences. Token `aud` must contain at least one configured audience when this list is set.
	Audiences []string `json:"audiences,omitempty"`
	// Required token scopes. Token must contain all configured scopes when this list is set.
	Scopes []string `json:"scopes,omitempty"`
	// JWKS fetch timeout as a Go duration string, for example `5s` or `1m`.
	JwksTimeout *string `json:"jwksTimeout,omitempty"`
	// Claim mappings for this custom issuer.
	ClaimMappings []IssuerClaimMapping `json:"claimMappings"`
	// Allows this issuer's static `orgName` mappings to duplicate static org names from other issuers.
	AllowDuplicateStaticOrgNames *bool `json:"allowDuplicateStaticOrgNames,omitempty"`
}

type _IssuerCreateRequest IssuerCreateRequest

// NewIssuerCreateRequest instantiates a new IssuerCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuerCreateRequest(name string, issuerUrl string, jwksUrl string, claimMappings []IssuerClaimMapping) *IssuerCreateRequest {
	this := IssuerCreateRequest{}
	this.Name = name
	this.IssuerUrl = issuerUrl
	this.JwksUrl = jwksUrl
	var origin string = "custom"
	this.Origin = &origin
	var serviceAccount bool = false
	this.ServiceAccount = &serviceAccount
	this.ClaimMappings = claimMappings
	var allowDuplicateStaticOrgNames bool = false
	this.AllowDuplicateStaticOrgNames = &allowDuplicateStaticOrgNames
	return &this
}

// NewIssuerCreateRequestWithDefaults instantiates a new IssuerCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerCreateRequestWithDefaults() *IssuerCreateRequest {
	this := IssuerCreateRequest{}
	var origin string = "custom"
	this.Origin = &origin
	var serviceAccount bool = false
	this.ServiceAccount = &serviceAccount
	var allowDuplicateStaticOrgNames bool = false
	this.AllowDuplicateStaticOrgNames = &allowDuplicateStaticOrgNames
	return &this
}

// GetName returns the Name field value
func (o *IssuerCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IssuerCreateRequest) SetName(v string) {
	o.Name = v
}

// GetIssuerUrl returns the IssuerUrl field value
func (o *IssuerCreateRequest) GetIssuerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetIssuerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerUrl, true
}

// SetIssuerUrl sets field value
func (o *IssuerCreateRequest) SetIssuerUrl(v string) {
	o.IssuerUrl = v
}

// GetJwksUrl returns the JwksUrl field value
func (o *IssuerCreateRequest) GetJwksUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JwksUrl
}

// GetJwksUrlOk returns a tuple with the JwksUrl field value
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetJwksUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JwksUrl, true
}

// SetJwksUrl sets field value
func (o *IssuerCreateRequest) SetJwksUrl(v string) {
	o.JwksUrl = v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *IssuerCreateRequest) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *IssuerCreateRequest) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *IssuerCreateRequest) SetOrigin(v string) {
	o.Origin = &v
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *IssuerCreateRequest) GetServiceAccount() bool {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret bool
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *IssuerCreateRequest) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given bool and assigns it to the ServiceAccount field.
func (o *IssuerCreateRequest) SetServiceAccount(v bool) {
	o.ServiceAccount = &v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *IssuerCreateRequest) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *IssuerCreateRequest) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *IssuerCreateRequest) SetAudiences(v []string) {
	o.Audiences = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *IssuerCreateRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *IssuerCreateRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *IssuerCreateRequest) SetScopes(v []string) {
	o.Scopes = v
}

// GetJwksTimeout returns the JwksTimeout field value if set, zero value otherwise.
func (o *IssuerCreateRequest) GetJwksTimeout() string {
	if o == nil || IsNil(o.JwksTimeout) {
		var ret string
		return ret
	}
	return *o.JwksTimeout
}

// GetJwksTimeoutOk returns a tuple with the JwksTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetJwksTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.JwksTimeout) {
		return nil, false
	}
	return o.JwksTimeout, true
}

// HasJwksTimeout returns a boolean if a field has been set.
func (o *IssuerCreateRequest) HasJwksTimeout() bool {
	if o != nil && !IsNil(o.JwksTimeout) {
		return true
	}

	return false
}

// SetJwksTimeout gets a reference to the given string and assigns it to the JwksTimeout field.
func (o *IssuerCreateRequest) SetJwksTimeout(v string) {
	o.JwksTimeout = &v
}

// GetClaimMappings returns the ClaimMappings field value
func (o *IssuerCreateRequest) GetClaimMappings() []IssuerClaimMapping {
	if o == nil {
		var ret []IssuerClaimMapping
		return ret
	}

	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetClaimMappingsOk() ([]IssuerClaimMapping, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClaimMappings, true
}

// SetClaimMappings sets field value
func (o *IssuerCreateRequest) SetClaimMappings(v []IssuerClaimMapping) {
	o.ClaimMappings = v
}

// GetAllowDuplicateStaticOrgNames returns the AllowDuplicateStaticOrgNames field value if set, zero value otherwise.
func (o *IssuerCreateRequest) GetAllowDuplicateStaticOrgNames() bool {
	if o == nil || IsNil(o.AllowDuplicateStaticOrgNames) {
		var ret bool
		return ret
	}
	return *o.AllowDuplicateStaticOrgNames
}

// GetAllowDuplicateStaticOrgNamesOk returns a tuple with the AllowDuplicateStaticOrgNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerCreateRequest) GetAllowDuplicateStaticOrgNamesOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowDuplicateStaticOrgNames) {
		return nil, false
	}
	return o.AllowDuplicateStaticOrgNames, true
}

// HasAllowDuplicateStaticOrgNames returns a boolean if a field has been set.
func (o *IssuerCreateRequest) HasAllowDuplicateStaticOrgNames() bool {
	if o != nil && !IsNil(o.AllowDuplicateStaticOrgNames) {
		return true
	}

	return false
}

// SetAllowDuplicateStaticOrgNames gets a reference to the given bool and assigns it to the AllowDuplicateStaticOrgNames field.
func (o *IssuerCreateRequest) SetAllowDuplicateStaticOrgNames(v bool) {
	o.AllowDuplicateStaticOrgNames = &v
}

func (o IssuerCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuerCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["issuerUrl"] = o.IssuerUrl
	toSerialize["jwksUrl"] = o.JwksUrl
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.ServiceAccount) {
		toSerialize["serviceAccount"] = o.ServiceAccount
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.JwksTimeout) {
		toSerialize["jwksTimeout"] = o.JwksTimeout
	}
	toSerialize["claimMappings"] = o.ClaimMappings
	if !IsNil(o.AllowDuplicateStaticOrgNames) {
		toSerialize["allowDuplicateStaticOrgNames"] = o.AllowDuplicateStaticOrgNames
	}
	return toSerialize, nil
}

func (o *IssuerCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"issuerUrl",
		"jwksUrl",
		"claimMappings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIssuerCreateRequest := _IssuerCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIssuerCreateRequest)

	if err != nil {
		return err
	}

	*o = IssuerCreateRequest(varIssuerCreateRequest)

	return err
}

type NullableIssuerCreateRequest struct {
	value *IssuerCreateRequest
	isSet bool
}

func (v NullableIssuerCreateRequest) Get() *IssuerCreateRequest {
	return v.value
}

func (v *NullableIssuerCreateRequest) Set(val *IssuerCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerCreateRequest(val *IssuerCreateRequest) *NullableIssuerCreateRequest {
	return &NullableIssuerCreateRequest{value: val, isSet: true}
}

func (v NullableIssuerCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
