// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Issuer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Issuer{}

// Issuer Dynamically registered custom OIDC issuer binding.
type Issuer struct {
	// Unique UUID v4 identifier for the issuer binding.
	Id string `json:"id"`
	// Human-readable name for the issuer binding.
	Name string `json:"name"`
	// Expected JWT `iss` claim value.
	IssuerUrl string `json:"issuerUrl"`
	// JWKS endpoint used to verify token signatures.
	JwksUrl string `json:"jwksUrl"`
	// Dynamic issuer origin. Dynamic registration supports only `custom`.
	Origin string `json:"origin"`
	// Always false for dynamic custom issuer registrations; service-account behavior is configured per claim mapping.
	ServiceAccount bool `json:"serviceAccount"`
	// Allowed token audiences.
	Audiences []string `json:"audiences,omitempty"`
	// Required token scopes.
	Scopes []string `json:"scopes,omitempty"`
	// JWKS fetch timeout as a Go duration string.
	JwksTimeout *string `json:"jwksTimeout,omitempty"`
	// Claim mappings for this custom issuer.
	ClaimMappings []IssuerClaimMapping `json:"claimMappings,omitempty"`
	// Allows this issuer's static `orgName` mappings to duplicate static org names from other issuers.
	AllowDuplicateStaticOrgNames bool `json:"allowDuplicateStaticOrgNames"`
	// Current JWKS reachability status.
	Status IssuerStatus `json:"status"`
	// Date/time when the issuer binding was created.
	Created time.Time `json:"created"`
	// Date/time when the issuer binding was last updated.
	Updated time.Time `json:"updated"`
}

type _Issuer Issuer

// NewIssuer instantiates a new Issuer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuer(id string, name string, issuerUrl string, jwksUrl string, origin string, serviceAccount bool, allowDuplicateStaticOrgNames bool, status IssuerStatus, created time.Time, updated time.Time) *Issuer {
	this := Issuer{}
	this.Id = id
	this.Name = name
	this.IssuerUrl = issuerUrl
	this.JwksUrl = jwksUrl
	this.Origin = origin
	this.ServiceAccount = serviceAccount
	this.AllowDuplicateStaticOrgNames = allowDuplicateStaticOrgNames
	this.Status = status
	this.Created = created
	this.Updated = updated
	return &this
}

// NewIssuerWithDefaults instantiates a new Issuer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerWithDefaults() *Issuer {
	this := Issuer{}
	return &this
}

// GetId returns the Id field value
func (o *Issuer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Issuer) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Issuer) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Issuer) SetName(v string) {
	o.Name = v
}

// GetIssuerUrl returns the IssuerUrl field value
func (o *Issuer) GetIssuerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetIssuerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerUrl, true
}

// SetIssuerUrl sets field value
func (o *Issuer) SetIssuerUrl(v string) {
	o.IssuerUrl = v
}

// GetJwksUrl returns the JwksUrl field value
func (o *Issuer) GetJwksUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JwksUrl
}

// GetJwksUrlOk returns a tuple with the JwksUrl field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetJwksUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JwksUrl, true
}

// SetJwksUrl sets field value
func (o *Issuer) SetJwksUrl(v string) {
	o.JwksUrl = v
}

// GetOrigin returns the Origin field value
func (o *Issuer) GetOrigin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Origin, true
}

// SetOrigin sets field value
func (o *Issuer) SetOrigin(v string) {
	o.Origin = v
}

// GetServiceAccount returns the ServiceAccount field value
func (o *Issuer) GetServiceAccount() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetServiceAccountOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccount, true
}

// SetServiceAccount sets field value
func (o *Issuer) SetServiceAccount(v bool) {
	o.ServiceAccount = v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *Issuer) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *Issuer) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *Issuer) SetAudiences(v []string) {
	o.Audiences = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *Issuer) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *Issuer) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *Issuer) SetScopes(v []string) {
	o.Scopes = v
}

// GetJwksTimeout returns the JwksTimeout field value if set, zero value otherwise.
func (o *Issuer) GetJwksTimeout() string {
	if o == nil || IsNil(o.JwksTimeout) {
		var ret string
		return ret
	}
	return *o.JwksTimeout
}

// GetJwksTimeoutOk returns a tuple with the JwksTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetJwksTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.JwksTimeout) {
		return nil, false
	}
	return o.JwksTimeout, true
}

// HasJwksTimeout returns a boolean if a field has been set.
func (o *Issuer) HasJwksTimeout() bool {
	if o != nil && !IsNil(o.JwksTimeout) {
		return true
	}

	return false
}

// SetJwksTimeout gets a reference to the given string and assigns it to the JwksTimeout field.
func (o *Issuer) SetJwksTimeout(v string) {
	o.JwksTimeout = &v
}

// GetClaimMappings returns the ClaimMappings field value if set, zero value otherwise.
func (o *Issuer) GetClaimMappings() []IssuerClaimMapping {
	if o == nil || IsNil(o.ClaimMappings) {
		var ret []IssuerClaimMapping
		return ret
	}
	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetClaimMappingsOk() ([]IssuerClaimMapping, bool) {
	if o == nil || IsNil(o.ClaimMappings) {
		return nil, false
	}
	return o.ClaimMappings, true
}

// HasClaimMappings returns a boolean if a field has been set.
func (o *Issuer) HasClaimMappings() bool {
	if o != nil && !IsNil(o.ClaimMappings) {
		return true
	}

	return false
}

// SetClaimMappings gets a reference to the given []IssuerClaimMapping and assigns it to the ClaimMappings field.
func (o *Issuer) SetClaimMappings(v []IssuerClaimMapping) {
	o.ClaimMappings = v
}

// GetAllowDuplicateStaticOrgNames returns the AllowDuplicateStaticOrgNames field value
func (o *Issuer) GetAllowDuplicateStaticOrgNames() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllowDuplicateStaticOrgNames
}

// GetAllowDuplicateStaticOrgNamesOk returns a tuple with the AllowDuplicateStaticOrgNames field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetAllowDuplicateStaticOrgNamesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowDuplicateStaticOrgNames, true
}

// SetAllowDuplicateStaticOrgNames sets field value
func (o *Issuer) SetAllowDuplicateStaticOrgNames(v bool) {
	o.AllowDuplicateStaticOrgNames = v
}

// GetStatus returns the Status field value
func (o *Issuer) GetStatus() IssuerStatus {
	if o == nil {
		var ret IssuerStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetStatusOk() (*IssuerStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Issuer) SetStatus(v IssuerStatus) {
	o.Status = v
}

// GetCreated returns the Created field value
func (o *Issuer) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Issuer) SetCreated(v time.Time) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *Issuer) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *Issuer) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *Issuer) SetUpdated(v time.Time) {
	o.Updated = v
}

func (o Issuer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Issuer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["issuerUrl"] = o.IssuerUrl
	toSerialize["jwksUrl"] = o.JwksUrl
	toSerialize["origin"] = o.Origin
	toSerialize["serviceAccount"] = o.ServiceAccount
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.JwksTimeout) {
		toSerialize["jwksTimeout"] = o.JwksTimeout
	}
	if !IsNil(o.ClaimMappings) {
		toSerialize["claimMappings"] = o.ClaimMappings
	}
	toSerialize["allowDuplicateStaticOrgNames"] = o.AllowDuplicateStaticOrgNames
	toSerialize["status"] = o.Status
	toSerialize["created"] = o.Created
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

func (o *Issuer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"issuerUrl",
		"jwksUrl",
		"origin",
		"serviceAccount",
		"allowDuplicateStaticOrgNames",
		"status",
		"created",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIssuer := _Issuer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIssuer)

	if err != nil {
		return err
	}

	*o = Issuer(varIssuer)

	return err
}

type NullableIssuer struct {
	value *Issuer
	isSet bool
}

func (v NullableIssuer) Get() *Issuer {
	return v.value
}

func (v *NullableIssuer) Set(val *Issuer) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuer) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuer(val *Issuer) *NullableIssuer {
	return &NullableIssuer{value: val, isSet: true}
}

func (v NullableIssuer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
